```yaml
   name: Run Spam Bot

   # Позволяет запускать код вручную через вкладку Actions
   on:
     workflow_dispatch:

   jobs:
     run-script:
       runs-on: ubuntu-latest
       steps:
         - name: Проверяем код из репозитория
           uses: actions/checkout@v4

         - name: Устанавливаем Node.js
           uses: actions/setup-node@v4
           with:
             node-version: 20

         - name: Запускаем наш скрипт
           run: node index.js
